backend:
  name: github
  repo: Rusta/www-sophie-ts
  branch: master

media_folder: "img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/about.md"
        label: "About"
        name: "about"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "pages/menu.md"
        label: "Menu"
        name: "menu"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "pages/contact-us.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
      - file: "pages/404.md"
        label: "404 - Not found"
        name: "404"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
  - name: "blog"
    folder: "pages/blog"
    label: "Blog"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "gallery"
    folder: "pages/gallery"
    label: "Gallery"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image Title"
            name: "imageTitle"
            widget: "string"
