backend:
  name: github
  repo: Rusta/www-sophie-ts
  branch: master

media_folder: "public/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
