backend:
  name: github
  repo: Rusta/www-sophie-ts
  branch: master

media_folder: "public/img"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "blob"
    folder: "pages/blog"
    label: "Blog"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
