backend:
  name: github
  repo: Rusta/www-sophie-ts
  branch: master

media_folder: "public/img"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "pages/contact-us.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "pages/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "pages/404.md"
        label: "404 - Not found"
        name: "404"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    folder: "pages/blog"
    label: "Blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "menu"
    folder: "pages/menu"
    label: "Menu"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
